server:
  port: 8080

spring:
  application:
    name: DoDiet-API
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET} # Must be >= 256 bits
  expiration: 86400000 # 1 day
  refresh-token-expiration: 2592000000 # 30 days

app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
  gemini:
    api-key: ${GEMINI_API_KEY:}
  firebase:
    config-path: ${FIREBASE_CONFIG_PATH:firebase-service-account.json}
